# Generated by Django 3.0.6 on 2020-05-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='order_product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='shopping_cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eshop.ShoppingCart'),
            preserve_default=False,
        ),
    ]
