# Generated by Django 3.0.6 on 2020-05-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20200523_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
