# Generated by Django 3.0.6 on 2020-05-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
